name: Latest PixiJS Node.js CI

on:
    push:
        branches: [ master, v7_dev ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
              with:
                path: tilemap
            - name: Go into tilemap directory
              run: cd tilemap && ls && cat package.json
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install npm
              run: npm install -g npm@9
            - name: Install dependencies
              run: cd tilemap && yarn
            - name: Build & type-checking
              run: cd tilemap && yarn build
            - name: Lint
              run: cd tilemap && yarn lint
            - uses: GabrielBB/xvfb-action@v1.0
              with:
                name: Unit testing
                run: cd tilemap && yarn unit-test


